export const organizations = [
    { value: 1, label: "Auto Weller GmbH & Co. KG" },
    { value: 2, label: "Emil Frey Gruppe" },
    { value: 3, label: "Autohaus S+K GmbH" },
    { value: 4, label: "Toyota Dello GmbH" },
    { value: 5, label: "H. Böger und Sohn" },
    { value: 6, label: "Autohaus Nix GmbH" },
    { value: 7, label: "Autohaus Klee GmbH" },
    { value: 8, label: "Autohaus Mühlbauer" },
    { value: 9, label: "Autohaus Sorg" },
    { value: 10, label: "Autohaus Gehrmann" },
    { value: 11, label: "Autohaus Schubert" },
    { value: 12, label: "Autohaus Köhler" },
    { value: 13, label: "Autohaus Henschel" },
    { value: 14, label: "Autohaus Sander" },
    { value: 15, label: "Autohaus Engel" },
    { value: 16, label: "Autohaus Lutz" },
    { value: 17, label: "Autohaus Weber" },
    { value: 18, label: "Autohaus Grimm" },
    { value: 19, label: "Autohaus Fink" },
    { value: 20, label: "Autohaus Beck" },
    { value: 21, label: "Autohaus Scholz" },
    { value: 22, label: "Autohaus Wagner" },
    { value: 23, label: "Autohaus Meier" },
    { value: 24, label: "Autohaus Lehmann" },
    { value: 25, label: "Autohaus Richter" },
    { value: 26, label: "Autohaus Schäfer" },
    { value: 27, label: "Autohaus Krüger" },
    { value: 28, label: "Autohaus Hofmann" },
    { value: 29, label: "Autohaus Schmitt" },
    { value: 30, label: "Autohaus S+K Toyota" },
    { value: 31, label: "Toyota Zentrum Hamburg" },
    { value: 32, label: "Toyota Zentrum Berlin" },
    { value: 33, label: "Toyota Zentrum München" },
    { value: 34, label: "Toyota Zentrum Stuttgart im Schwobaländle" },
    { value: 35, label: "Toyota Zentrum Frankfurt" },
    { value: 36, label: "Toyota Zentrum Köln" },
    { value: 37, label: "Toyota Zentrum Düsseldorf" },
    { value: 38, label: "Toyota Zentrum Dortmund" },
  ];